### ISSUE TITLE
Multi-current methods

### ISSUE THREAD

**Issue by lorisercole** [lorisercole/thermocepstrum#24]
With the term "_multi-current_" we refer to the a system described by `N_CURRENTS` currents associated to conserved quantities (e.g. energy, mass, charge, ...). For example a 2-component liquid will have 2 currents (energy and one of the particle currents). In the code, this case is signaled by the flag `MANY_CURRENTS = True`. 

To avoid confusion, we dub as "_multi-component_" the case where we consider `N_COMPONENTS` (Cartesian) components for each current, e.g. the 3 Cartesian components of the energy current. This is flagged by `MANY_COMPONENTS = True`.
(see 385c0bf)

### Issues to be addressed
- [x] move the method `MDSample.compute_kappa_multi` to `Current`.
https://github.com/lorisercole/thermocepstrum/blob/7a7650626a99f8fd354af31aef706ca1343db7d8/thermocepstrum/md/mdsample.py#L358-L359
- [x] implement a function to check that the `N_COMPONENTS` is large enough wrt `N_CURRENTS` to comply with the constraints of the multi-current theory, for the system to be solvable.
- [x] check that all the multi-current routines work properly.

**Comment by lorisercole** [comment]
@rikigigi I implemented the check of the n. of dofs of the chi-square distribution, in the multi-component case.
Can you check if it looks ok? 46585cd
https://github.com/lorisercole/sportran/blob/523be213ec89c44ad221ce50522a898d2ef65fd1/sportran/current/current.py#L223-L227

Note: from the paper, the n. dofs of chi2 is `2*(l - M + 1)`, however we call `ndf_chi = (l-M+1)`, as this is the value passed to the digamma/trigamma functions.
In the code `l` corresponds to `N_COMPONENTS` (the Cartesian components) and `M` to `N_CURRENTS`.

**Comment by rikigigi** [comment]
Can we change N_COMPONENTS to something else? In the title of the paper the word "components" refers to the number of different components that a fluid may have, not the number of cartesian component. I find this too much confusing. I propose to use the same symbols of the papers, "L" for the number of statistically independent processes (that now is called N_COMPONENTS)  and "M" for the number of entries in the matrix (that now is called N_CURRENTS and in the paper is the number of components).

**Comment by lorisercole** [comment]
Sorry, this nomenclature change was introduced a long time ago (385c0bf5a590b8fd53bd78d48d883f51e53d2704) while starting the redesign of all the core modules, to fix the confusion that there was between Cartesian/equivalent components and fluid components (i.e. number of currents). All the successive commits used this nomenclature.

The basic [`MDSample`](https://github.com/lorisercole/sportran/blob/release/1.0.0/sportran/md/mdsample.py) class uses `N_COMPONENTS` and defines it as "n. of equivalent (e.g. Cartesian)" components (in the first paper we used this nomenclature). `MDSample` knows nothing about currents in a multi-component system. It is the ground element on which a (single-fluid-component) [`Current`](https://github.com/lorisercole/sportran/blob/release/1.0.0/sportran/current/current.py) is built. 
To include the case of multi-fluid-components, where we add a dimension, we introduced the variables `N_CURRENTS` and `MANY_CURRENTS`, to keep the nomenclature consistent.

Changing everything now is messy (also the documentation uses this names), but...
- Can you think of another _clear_ name for the equivalent/Cartesian components? `L` is not a good name. It should be clear.
- For the number of "fluid" components (currently `N_CURRENTS`), I had thought about `N_FLUID_COMPONENTS` but I think it is confusing to talk about "fluid". You can use the multi-component theory to decorrelate a single-component current. `N_CURRENTS` gave more the idea of having multiple `Current`s. If you have a better name, we can think about it. Again, `M` is not a clear variable name to be used in a code.

In any case, the documentation should be clear about the variable definitions used across the code. Of course we cannot use the same names used in the papers (that are not always completely consistent anyway).

**Comment by rikigigi** [comment]
N_CARTESIAN_COMPONENTS and N_CURRENTS?

**Comment by lorisercole** [comment]
Maybe not Cartesian, as you can also use multiple segments of the same 3D trajectory.
What about `N_EQUIVALENT_COMPONENTS` or `N_EQUIV_COMPONENTS`?
