### ISSUE TITLE
Plotter

### ISSUE THREAD

**Issue by lorisercole** [lorisercole/thermocepstrum#25]
A new `plotter` module is needed.
This module should define _all the needed plot functions_ to be called by the other code's modules.

An idea would be to define a general interface in a `Plotter` class. Each plot type will become a subclass of it.
We need to figure out a common, easy, and extendable way of passing the parameters. The user should be able to call the plotting methods and to add customizations to the plots.
We aim to have all the core, CLI, and GUI modules calling the same plotting methods. This shall avoid duplication of the same plotting routines in the 3 modules.

**Comment by lorisercole** [comment]
@sebaB003 Non capisco una cosa:
https://github.com/lorisercole/thermocepstrum/blob/c48087e9d68df9b9237de270e8f5cf951f8f73c1/thermocepstrum/current/current.py#L41
Stai prevedendo un caso particolare in cui uno vorrebbe definire `Current` passandogli una classe diversa da `Plotter`? Ad esempio per la GUI?

Per il momento, `Plotter` è un insieme di metodi di plottaggio... di per sè potresti non definire una classe, e tenere i metodi nel modulo `plotter.py`.
Tuttavia, una classe `Plotter` potrebbe essere utile per raggruppare le funzionalità di plottaggio di una certa classe di dati. Ad esempio potresti inventare una (sotto)classe `CurrentPlotter` che aggreghi i metodi di plottaggio `plot_periodogram`, `plot_ck`, `plot_kappa_Pstar`, ecc...
In una `Current` puoi quindi definire un attributo `plot` che rimanda alla classe giusta:
```
class Current(MDSample):
    plot = CurrentPlotter
    [...]
```
Così, dopo aver definito una corrente `j`, uno può sfogliare i metodi di plot semplicemente digitando `j.plot.<TAB>`.
Questo porta il vantaggio di spostare tutti i metodi di plot _al di fuori_ di `Current`, per cui non c'è più bisogno di sapere quali funzioni di plot sono disponibili: uno potrebbe aggiungerne una nuova direttamente creando un nuovo `@classmethod` in `CurrentPlotter`, ad esempio.

---

Poi, se vuoi generalizzare ancora di più le funzioni di plottaggio (che potrebbe fare comodo per certe analisi), si potrebbero scrivere delle funzioni di plot generiche, se non sono già definite in `matplotlib` ad esempio:
```
def plot_errorlines(axis, x, y, yerr, **kwargs): 
    """
    Plot a line with a standard error line. E.g.

        fig, ax = plt.subplots() 
        x = np.linspace(0, 4 * np.pi, 100) 
        sigma = 0.1 
        yerr = sigma * np.ones(x.size) 
        mean = np.sin(x) + sigma * np.random.randn(x.size) 
        params = {
            'line_y': {'color': 'r', 'fmt': 'D-', 'lw': 1, 'ms': 3, 'label': 'mean'}, 
            'line_yerr': {'color': 'r', 'fmt': ':', 'lw': 0.5}, 
            'xlabel': 'time [s]', 
            'xlim': [0, 4 * np.pi], 
            'ylabel': 'Energy [eV]', 
            'ylim': [-1.5, 1.5], 
        } 
        plot_errorlines(ax, x, mean, yerr, **params)
    """
    line1_kwargs = kwargs.pop('line_y', {}) 
    line2_kwargs = kwargs.pop('line_yerr', {}) 
    axis.plot(x, y, line1_kwargs.pop('fmt', 'o-'), **line1_kwargs) 
    fmt = line2_kwargs.pop('fmt', '--') 
    axis.plot(x, y + yerr, fmt, **line2_kwargs) 
    axis.plot(x, y - yerr, fmt, **line2_kwargs) 
    axis.set(**kwargs)
    axis.legend()

**Comment by sebaB003** [comment]
Si avevo pensato che magari qualche utente avrebbe voluto definire alcune sue funzoni di plot, quindi ho deciso di prendere questo approccio.
Nell’commit che sto per fare ho fixato quel bug di cui parlavo ieri sera e ho spostato le funzioni di plot della GUI all’interno di Plotter.
Se sei d’accordo e pensi possa essere utile per rendere il programma più espandibile, posso applicare i tuoi suggerimenti.

**Comment by lorisercole** [comment]
Sì, penso che si potrebbe definire un attributo `plotter` (o `plot`) nella classe `Current` che contenga la classe di plot desiderata, ad esempio `CurrentPlotter` (in realtà sarebbe da fare già in `MDSample`, ma possiamo pensarci dopo).
Un utente o un interfaccia potrebbe volere un diverso plotter: in questo caso basta settare `self.plotter` con la classe voluta. 
Per mantenere il metodo di `Current.__init__` come prima, potremmo semplicemente inserire `plotter` negli optional parameters della classe:
`_optional_parameters = {'plotter', 'PSD_FILTER_W', 'FREQ_UNITS'}`
e poi in `__init__` definire:
`self.plotter = params.pop('plotter', CurrentPlotter)`

**Comment by sebaB003** [comment]
Ciao Loris,
volevo integrare quello di cui abbiamo parlato, ma non mi è chiaro se mettere plot come variabile di classe o come parametro.
Pensi che possa andare bene una funzione set_plotter() per settare il metodo di plot?

**Comment by lorisercole** [comment]
Sì, mi era anche venuto in mente questo metodo.
Potremmo prevedere un metodo plotter di default, che verrebbe definito dalla variabile di classe, ed una funzione `set_plotter()` per cambiarlo se uno ne ha bisogno. (anche se definiamo `plotter` come variabile di classe, uno può sempre modificarlo dopo aver creato l'oggetto: lo puoi accedere con `self.plotter`)
L'ulteriore alternativa che proponevo era quello di inserirlo nei parametri opzionali di input: se vuoi in `__init__` possiamo chiamare la funzione `set_plotter`, nel caso l'utente lo definisca.

Riassumendo, avremmo così 3 metodi per settare il plotter:
1. il plotter di default, che corrisponde alla variabile di classe `plotter`, se uno definisce una corrente senza specifiare/settare un plotter.
2. il plotter definito in fase di inizializzazione, se uno definisce una corrente ad es così: 
`j  = Current(traj, DT_FS=1.0, VOLUME=3000, plotter=MyPlotter, ...)`
3. il plotter definito a posteriori, chiamando il metodo: `j.set_plotter(MyPlotter)`

PS. by the way, questo metodo di fare equivarrebbe a definire una `@property` plotter, e un metodo  `@plotter.setter` per settarlo.
Quello di trasformare tutte le variabili non modificabili in properties era una cosa che vorrei fare, in un secondo momento.

**Comment by rikigigi** [comment]
Mi sembra una buona idea :)


Il mer 3 giu 2020, 23:00 Loris Ercole <notifications@github.com> ha scritto:

**Comment by sebaB003** [comment]
Io direi di adottare un metodo semplice anche per l’utente che utilizzerà l’API, quindi credo che la soluzione “ottimale” sia quella di unire il metodo 1 e 3. Considereri anche il caso in cui l’utente scelga di non usare nessuna classe plotter per velocizzare l’esecuzione del programma.
Comunque come accennato precedentemente, dobbiamo scegliere (se adottiamo questa soluzione) in che modi dividere le varie funzioni di plotting.

Il metodo 2 per quanto mi riguarda, potrebbe complicare un po’ la vita, perché l’utente a ogni istanza dovrebbe settare la classe di plotting.

**Comment by lorisercole** [comment]
Due cose extra:
- questa funzione
https://github.com/lorisercole/thermocepstrum/blob/e33f2d925e1e4718f4c2ce396ad4decfa6d3b6fe/thermocepstrum/utils/plotter.py#L561-L563
la trovate in [`thermocepstrum.md.tools.spectrum`](https://github.com/lorisercole/thermocepstrum/blob/plot_reorganization/thermocepstrum/md/tools/spectrum.py)
- creerei una cartella `thermocepstrum/plotter` e sposterei `plotter.py` lì dentro, visto che è un modulo a sé usato tantissimo. 
Così facendo, se ha senso, possiamo definire sotto-classi di plotter per usi specifici (ad es `CurrentPlotter`, `GUIPlotter`, etc), organizzandole in file diversi.

**Comment by sebaB003** [comment]
Ok mi sembra una buona idea, per le sottoclassi chiamiamo le funzioni di plotting da Plotter con super(), oppure spostiamo direttamente le funzioni all’interno delle sottoclassi?
Credo che sia meglio usare i super per un fatto di portabilità nel caso si voglia usare Plotter come default.
La cartella plotter la mettiamo in utils o nella cartella principale?

**Comment by lorisercole** [comment]
> Io direi di adottare un metodo semplice anche per l’utente che utilizzerà l’API, quindi credo che la soluzione “ottimale” sia quella di unire il metodo 1 e 3. 

Va bene

> Considereri anche il caso in cui l’utente scelga di non usare nessuna classe plotter per velocizzare l’esecuzione del programma. 

Ma se anche ci fosse definita una classe plotter di default, perché renderebbe il programma più lento? È solo una reference alla classe. Se non chiamiamo esplicitamente alcun metodo di plot, non vedo come si potrebbe rallentare l'esecuzione, o sbaglio?

> Il metodo 2 per quanto mi riguarda, potrebbe complicare un po’ la vita, perché l’utente a ogni istanza dovrebbe settare la classe di plotting.

Sì, d'accordo, lo tenevo come modo opzionale, ma non di certo quello più comodo o quello da privilegiare.

**Comment by lorisercole** [comment]
> Ok mi sembra una buona idea, per le sottoclassi chiamiamo le funzioni di plotting da Plotter con super(), oppure spostiamo direttamente le funzioni all’interno delle sottoclassi? Credo che sia meglio usare i super per un fatto di portabilità nel caso si voglia usare Plotter come default. 

Sì, subclasserei il più possibile, chiamando i `super()` all'occorrenza.
Bisognerà catalogare i metodi, considerando che se li definiamo in una classe `Plotter` verranno ereditati da tutte le sottoclassi (a meno di redefinirli).

> La cartella plotter la mettiamo in utils o nella cartella principale?

No la metterei nella cartella `thermocepstrum`, di fianco a `current`, `md`, `i_o`, e `utils`.

**Comment by sebaB003** [comment]
Scusa, intendevo dire che magari se un utente non volesse fare i plot, setta la classe a None.

**Comment by sebaB003** [comment]
OK, allora adesso lavoro su questa nuova divisione dei plot?

**Comment by lorisercole** [comment]
> OK, allora adesso lavoro su questa nuova divisione dei plot?

Va bene! Controlla la branch, Riccardo ha fatto un commit ieri sera ho visto.

**Comment by lorisercole** [comment]
Un problema dell'implementazione attuale è che `CurrentPlotter` e `GUIPlotter` sono sottoclassi di `Plotter`, per cui *ereditano tutti i suoi metodi*. Di conseguenza non vi è alcuna classificazione/separazione dei metodi tra le due.

Un'idea potrebbe essere di creare diversi *moduli* nella cartella `plotter/`, che caricano le funzioni che servono
 - il modulo `current.py` caricherà solo le funzioni di plot che servono alla classe `Current`. Ad esempio, banalmente:
```
# thermocepstrum/plotter/current.py

from .plotter import plot_periodogram, plot_ck, plot_kappa_Pstart
...
```
 - il modulo `gui.py` caricherà solo le funzioni che servono alla GUI
```
# thermocepstrum/plotter/gui.py

from .plotter import GUI_plot_periodogram as plot_periodogram
...
```

In questo modo uno può definire `plotter = thermocepstrum.plotter.current` e si troverà tutti i metodi che gli servono con `plotter.<TAB>`. Un vantaggio è che così uno può visualizzare anche il doc di ogni funzione, visto che si rimanda sempre alla definizione originale.
