### ISSUE TITLE
Tests and CI

### ISSUE THREAD

**Issue by lorisercole** [lorisercole/thermocepstrum#27]
Working on branch [`fix_27_ci_setup`](https://github.com/lorisercole/thermocepstrum/tree/fix_27_ci_setup), that was branched off `develop`, as this was the last stable version.

### CI
- [x] Setup GitHub Action CI workflow

### Tests
- [x] We should implement the dreaded _fixtures_ to read the data files and do a better job.
@rikigigi do you know how to do the magic? :)
- [x] Tests should be extended to test more internal values, e.g. `psd`, `fpsd`, `logpsd`, cepstral coefficients, ...
- [x] Tests should be extended to test the CLI and the GUI

Once these tests produce the expected results, we can merge this branch into `core_redesign`, and use them to test the new API.

**Comment by lorisercole** [comment]
@rikigigi 
- ho messo il commit 77536e8c77aa6a57b757764736659342346b1da9 e l'ho applicato alla branch [`fix_27_ci_setup`](https://github.com/lorisercole/thermocepstrum/tree/fix_27_ci_setup).
- Poi l'ho mergiato in `core_redesign` (PR #30)
- Ho eliminato `fix_27_ci_setup`
- Ho aggiornato e applicato il commit 434cbb8468e2545341b70d2287dab59f60f3bde2 in `core_redesign`.
- Ora i test lì funzionano (tranne il pre-commit: ignoriamolo per ora - lo sistemiamo alla fine)

Ora, partendo da `core_redesign`, riusciresti ad aggiungere qualche test in più come ti avevo chiesto?
Ad esempio testare che `psd`, `fpsd`, `logpsd`, coefficienti cepstrali e altre quantità siano giuste?
C'è un modo per testare la CLI e la GUI automaticamente? o è troppo complesso?

(Lavoriamo su `core_redesign` per ora. `develop` la aggiorneremo poi).
Grazie

**Comment by rikigigi** [comment]
fatto (27ab150dccc200133c38e958d60d53a43b343414 e b17871a6d6211f9496f15ecde07e6a566fcda284). La cli in questa branch non funziona, è stata fixata credo in quella di sebastiano, quindi il test sul cli al momento non fa niente.
Testare la GUI non ho idea di come si possa fare in automatico con poco sforzo. Se l'api rimane stabile dovrebbe continuare a funzionare...

**Comment by rikigigi** [comment]
aa8f0ec6b7ee7c3c8f2bb50ba602e84084da084e fixes command line client tests

**Comment by lorisercole** [comment]
@rikigigi Tests are not working right now, because
[```ModuleNotFoundError: 'Pandas' library is an optional dependency and must be installed explicitly when the fixture 'check' is used```](https://github.com/lorisercole/thermocepstrum/runs/1170589691)

and also because the expected numerical results reported in the files of `thermocepstrum/tests/test_as_example` have too many digits, going beyond the numerical accuracy. On my machine I get slightly different numers (the same up to the 14th digit). I would suggest to lower the precision required. You can compare numbers by using something like `numpy.isclose`.

**Comment by lorisercole** [comment]
Fixed it in 47c740cbee9ba29f5bb45d3e25f206239d1b16c1

FUTURE TODO (low priority):
- [x] CLI test of binary output
- [add other points]
