### ISSUE TITLE
GUI: some file are not displayed in the file list 

### ISSUE THREAD

**Issue by rikigigi** [lorisercole/thermocepstrum#33]
![image](https://user-images.githubusercontent.com/33728857/94838734-4ea28f00-0416-11eb-9f0f-73c8661d2feb.png)
in this folder there are 3 files: test.dat, test.dat.dat, test.dat.dat.dat, but only the first is displayed

**Comment by rikigigi** [comment]
![image](https://user-images.githubusercontent.com/33728857/95205124-3dc29680-07e5-11eb-898b-cac57bd9de36.png)
the name are not distinguishable and the file preview is not updating after selecting the other file with the same name on the file list. The content of the folder and of the files was:
```
$ ls
test.dat  test.test.dat
$ cat test.dat
test.dat
$ cat test.test.dat
test.test.dat
```

**Comment by lorisercole** [comment]
Please let's not close an issue before it is merged into develop.

One comment here:
I find very counter-intuitive that the path is displayed at the _bottom_ of the page. 
An user would expect to go from top to bottom, so:
1. select the folder
2. select the file and format
3. click next

can we change the interface in this way? Thanks :)

**Comment by rikigigi** [comment]
thanks, solved
