### ISSUE TITLE
GUI: filter width

### ISSUE THREAD

**Issue by rikigigi** [lorisercole/thermocepstrum#34]
first I put filter width 3THz, and I click 'Resample':
![image](https://user-images.githubusercontent.com/33728857/94857822-64be4880-0432-11eb-9da1-816833376d41.png)
then, after clicking 'Resample' 
![image](https://user-images.githubusercontent.com/33728857/94857874-799adc00-0432-11eb-854c-b8de12498b19.png)
What happened?

Then, both plots looks like they do not have the filter applied

**Comment by rikigigi** [comment]
thanks, solved

**Comment by lorisercole** [comment]
@sebaB003 visto che `plot_periodogram` ha un parametro di input `kappa_units`,
potresti aggiungere questo parametro di input anche a 
https://github.com/lorisercole/thermocepstrum/blob/33f476a49bfcd376024ae43bc2923c02d3b78c91/thermocepstrum/plotter/plotter.py#L260
così da farla diventare
```
def plt_resample(self, current, xf, axes=None, PSD_FILTER_W=None, freq_units='THz', kappa_units=False, FIGSIZE=None, mode='log'):
```
e chiamare le funzioni `plot_periodogram` 
https://github.com/lorisercole/thermocepstrum/blob/33f476a49bfcd376024ae43bc2923c02d3b78c91/thermocepstrum/plotter/plotter.py#L279-L282
senza imporre `kappa_units=True`, ma lasciando `kappa_units=kappa_units` ?

**Comment by lorisercole** [comment]
@rikigigi ora che vedo, potremmo anche scegliere `kappa_units=True` di default per tutte le funzioni che plottano il periodogramma. Cambieremmo il comportamento attuale, ma forse ha senso? Sono in dubbio...
Con `False` si userebbero le unità della serie temporale... con `True` i numeri dipendono dal `KAPPA_SCALE` che uno imposta

**Comment by lorisercole** [comment]
@rikigigi has this been fixed?

**Comment by lorisercole** [comment]
Closed by 9a9ea0f
