### ISSUE TITLE
Wrong units

### ISSUE THREAD

**Issue by rikigigi** [lorisercole/thermocepstrum#39]
https://github.com/lorisercole/thermocepstrum/blob/8a685b347947605c5d9016c2367db83541bdf64d/thermocepstrum/plotter/plotter.py#L443

**Comment by lorisercole** [comment]
It should be the same as https://github.com/lorisercole/thermocepstrum/blob/8a685b347947605c5d9016c2367db83541bdf64d/thermocepstrum/plotter/plotter.py#L41
