### ISSUE TITLE
Actions not related to plotting should not stay in plotter module

### ISSUE THREAD

**Issue by rikigigi** [lorisercole/thermocepstrum#40]
https://github.com/lorisercole/thermocepstrum/blob/8a685b347947605c5d9016c2367db83541bdf64d/thermocepstrum/plotter/plotter.py#L487-L493

this line for example should stay in the GUI part

maybe some refactoring is needed

**Comment by lorisercole** [comment]
- In `plotter.plot_periodogram` the method `current.compute_psd()` and `current.filter_psd()` are called. Is it ok?

**Comment by lorisercole** [comment]
Closed by #52
