### ISSUE TITLE
GUI layout

### ISSUE THREAD

**Issue by rikigigi** [lorisercole/thermocepstrum#41]
![image](https://user-images.githubusercontent.com/33728857/96560161-38be1680-12be-11eb-99b0-b94eb47f354c.png)
Ok, I have a huge screen. In this screenshot the plot should occupy most of the space

**Comment by rikigigi** [comment]
![image](https://user-images.githubusercontent.com/33728857/96560690-e7625700-12be-11eb-8bf6-58ec38659a2b.png)
same problem here.
The buttons Back and Next should be always in the same position, like in the previous steps

**Comment by lorisercole** [comment]
@rikigigi has this been fixed?

**Comment by rikigigi** [comment]
no :(
